### ISSUE TITLE
IP address visible in codebase

### ISSUE THREAD

**Issue by OnomatoWomba** [JermaSites/fireman-weather#1]
I'm leaving this issue assuming that the IP address of @sticks-stuff that is visible in the file weather.js as a hard-coded variable.

This could be a completely different IP address entirely, but I'm letting you know in case you were unaware.

This was not given an environment variable and I'm assuming you don't want your personal data in the open.

**Comment by poespas** [comment]
Nice find.. :grin: I just DMd Sticks aswell about it !

**Comment by sticks-stuff** [comment]
That’s not my IP, I’ll remove it anyway though.
